last: 1000
images:
  docker.io:
    - hiromuhota/webspoo
    - imroc/logrotate
    - bitnami/nginx
    - linuxserver/nginx
    - calico/node
    - calico/typha
    - calico/cni
    - calico/kube-controllers
    - calico/pod2daemon-flexvol
    - flannel/flannel
    - flannel/flannel-cni-plugin
    - apache/seata-server
    - linuxserver/nginx
    - linuxserver/wps-office
    - linuxserver/wireguard
    - linuxserver/transmission
    - linuxserver/filebrowser
    - linuxserver/bookstack
    - linuxserver/nextcloud
    - linuxserver/owncloud
    - linuxserver/gitea
    - linuxserver/mariadb
    - linuxserver/mongodb
    - linuxserver/redis
    - linuxserver/postgres
    - linuxserver/plex
    - linuxserver/sonar
    - linuxserver/radar
    - linuxserver/emby    
  lscr.io:
    - linuxserver/nginx
    - linuxserver/wps-office
    - linuxserver/wireguard
    - linuxserver/transmission
    - linuxserver/filebrowser
    - linuxserver/bookstack
    - linuxserver/nextcloud
    - linuxserver/owncloud
    - linuxserver/gitea
    - linuxserver/mariadb
    - linuxserver/mongodb
    - linuxserver/redis
    - linuxserver/postgres
    - linuxserver/plex
    - linuxserver/sonar
    - linuxserver/radar
    - linuxserver/emby
  docker.elastic.co:
    - elasticsearch/elasticsearch
    - kibana/kibana
    - logstash/logstash
    - beats/filebeat
    - beats/heartbeat
    - beats/packetbeat
    - beats/auditbeat
    - beats/journalbeat
    - beats/metricbeat
    - apm/apm-server
    - app-search/app-search
  quay.io:
    - coreos/flannel
    - ceph/ceph
    - cephcsi/cephcsi
    - csiaddons/k8s-sidecar
    - csiaddons/volumereplication-operator
    - prometheus/prometheus
    - prometheus/alertmanager
    - prometheus/pushgateway
    - prometheus/blackbox-exporter
    - prometheus/node-exporter
    - prometheus-operator/prometheus-config-reloader
    - prometheus-operator/prometheus-operator
    - brancz/kube-rbac-proxy
    - cilium/cilium
    - cilium/tetragon
    - cilium/operator
    - cilium/operator-generic
    - thanos/thanos
    - cilium/certgen
    - cilium/hubble-relay
    - cilium/hubble-ui
    - cilium/hubble-ui-backend
    - cilium/hubble-ui
    - cilium/cilium-envoy
    - cilium/cilium-etcd-operator
    - cilium/operator
    - cilium/startup-script
    - cilium/clustermesh-apiserver
    - coreos/etcd
  k8s.gcr.io:
    - dns/k8s-dns-node-cache
    - metrics-server/metrics-server
    - kube-state-metrics/kube-state-metrics
    - prometheus-adapter/prometheus-adapter
    - sig-storage/nfs-subdir-external-provisioner
    - sig-storage/csi-node-driver-registrar
    - sig-storage/csi-provisioner
    - sig-storage/csi-resizer
    - sig-storage/csi-snapshotter
    - sig-storage/csi-attacher
    - sig-storage/nfsplugin
  registry.k8s.io:
    - pause
    - etcd
    - conformance
    - kube-proxy
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - coredns/coredns
    - ingress-nginx/controller
    - ingress-nginx/controller-chroot
    - ingress-nginx/kube-webhook-certgen
    - metrics-server/metrics-server
    - dns/k8s-dns-node-cache
    - sig-storage/nfs-subdir-external-provisioner
    - sig-storage/csi-node-driver-registrar
    - sig-storage/csi-provisioner
    - sig-storage/csi-resizer
    - sig-storage/csi-snapshotter
    - sig-storage/csi-attacher
    - kube-state-metrics/kube-state-metrics
    - prometheus-adapter/prometheus-adapter
  gcr.io:
    - kaniko-project/executor
    - google-samples/xtrabackup
  ghcr.io:
    - coroot/coroot
    - coroot/coroot-cluster-agent
    - coroot/coroot-node-agent
