name: Sync Images to Aliyun

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
    paths:
      - 'config.yaml'
      - 'custom_sync.yaml'
      - '.github/workflows/sync-images.yml'

env:
  HUB_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  HUB_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
  HUB_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  REPO_NAMESPACE: ctrimg

jobs:
  sync-images:
    name: Sync Images
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6小时超时

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: Install skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo

    - name: Login to Aliyun Registry
      run: |
        skopeo login -u "$HUB_USERNAME" -p "$HUB_PASSWORD" "$HUB_REGISTRY"

    - name: Run image synchronization
      run: |
        python generate_sync.py

    - name: Upload sync logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sync-logs
        path: |
          sync.log
          sync.yaml
          custom_sync.yaml

    - name: Notify completion
      if: always()
      run: |
        echo "镜像同步任务完成"
        if [ -f "sync.log" ]; then
          echo "同步结果摘要:"
          tail -n 20 sync.log
        fi